users = {
    "Carla": {
        "Visão computacional": 3.5,
        "Design": 2.0,
        "Redes neurais": 4.5,
        "Desenvolvimento de jogos": 5.0,
        "Desenvolvimento Web": 1.5,
        "Data science": 2.5,
        "Automação de testes": 2.0,
    },
    "Fernando": {
        "Visão computacional": 2.0,
        "Design": 3.5,
        "LGPD": 4.0,
        "Desenvolvimento de jogos": 2.0,
        "Desenvolvimento Web": 3.5,
        "Automação de testes": 3.0,
    },
    "Julio": {
        "Visão computacional": 5.0,
        "Design": 1.0,
        "LGPD": 1.0,
        "Redes neurais": 3.0,
        "Desenvolvimento de jogos": 5,
        "Desenvolvimento Web": 1.0,
    },
    "Lucas": {
        "Visão computacional": 3.0,
        "Design": 4.0,
        "LGPD": 4.5,
        "Desenvolvimento de jogos": 3.0,
        "Desenvolvimento Web": 4.5,
        "Data science": 4.0,
        "Automação de testes": 2.0,
    },
    "Ana": {
        "Design": 4.0,
        "LGPD": 1.0,
        "Redes neurais": 4.0,
        "Data science": 4.0,
        "Automação de testes": 1.0,
    },
    "Bruna": {
        "Design": 4.5,
        "LGPD": 4.0,
        "Redes neurais": 5.0,
        "Desenvolvimento de jogos": 5.0,
        "Desenvolvimento Web": 4.5,
        "Data science": 4.0,
        "Automação de testes": 4.0,
    },
    "Renato": {
        "Visão computacional": 5.0,
        "Design": 2.0,
        "Redes neurais": 3.0,
        "Desenvolvimento de jogos": 5.0,
        "Desenvolvimento Web": 4.0,
        "Data science": 5.0,
    },
    "Giovanna": {
        "Visão computacional": 3.0,
        "Redes neurais": 5.0,
        "Desenvolvimento de jogos": 4.0,
        "Desenvolvimento Web": 2.5,
        "Data science": 3.0,
    },
    "Leonardo": {
        "Visão computacional": 3.5,
        "Design": 3.0,
        "Desenvolvimento de jogos": 1.0,
        "Data science": 4.0,
    },
    "Lorena": {
        "Design": 1.0,
        "Redes neurais": 3.0,
        "Data science": 5.0,
        "Automação de testes": 2.5,
    },
    "João": {
        "Visão computacional": 4.0,
        "Design": 3.0,
        "Redes neurais": 1.5,
        "Desenvolvimento de jogos": 3.5,
        "Desenvolvimento Web": 1.0,
        "Data science": 4.5,
        "Automação de testes": 2.0,
    },
    "Mariana": {
        "Visão computacional": 1.0,
        "Design": 4.5,
        "Redes neurais": 3.0,
        "Desenvolvimento de jogos": 2.5,
        "Desenvolvimento Web": 1.0,
        "Data science": 3.5,
        "Automação de testes": 1.5,
    },
    "Pedro": {
        "Visão computacional": 3.0,
        "Design": 1.5,
        "Redes neurais": 4.0,
        "Desenvolvimento de jogos": 3.0,
        "Desenvolvimento Web": 2.5,
        "Data science": 1.0,
        "Automação de testes": 3.5,
    },
    "Camila": {
        "Visão computacional": 1.0,
        "Design": 3.5,
        "Redes neurais": 2.0,
        "Desenvolvimento de jogos": 4.0,
        "Desenvolvimento Web": 2.0,
        "Data science": 4.5,
        "Automação de testes": 1.5,
    },
    "Rafael": {
        "Visão computacional": 3.0,
        "Design": 2.0,
        "Redes neurais": 4.5,
        "Desenvolvimento de jogos": 2.5,
        "Desenvolvimento Web": 1.0,
        "Data science": 3.5,
        "Automação de testes": 2.0,
    },
    "Amanda": {
        "Visão computacional": 2.0,
        "Design": 1.0,
        "Redes neurais": 4.0,
        "Desenvolvimento de jogos": 1.0,
        "Desenvolvimento Web": 4.0,
        "Data science": 1.5,
        "Automação de testes": 4.5,
    },
    "Diego": {
        "Visão computacional": 4.5,
        "Design": 2.5,
        "Redes neurais": 1.0,
        "Desenvolvimento de jogos": 2.0,
        "Desenvolvimento Web": 3.5,
        "Data science": 4.5,
        "Automação de testes": 2.0,
    },
    "Isabela": {
        "Visão computacional": 1.5,
        "Design": 3.5,
        "Redes neurais": 3.0,
        "Desenvolvimento de jogos": 3.5,
        "Desenvolvimento Web": 4.5,
        "Data science": 2.0,
        "Automação de testes": 1.0,
    },
    "Eduardo": {
        "Visão computacional": 4.0,
        "Design": 1.5,
        "Redes neurais": 1.5,
        "Desenvolvimento de jogos": 4.5,
        "Desenvolvimento Web": 2.5,
        "Data science": 1.5,
        "Automação de testes": 3.0,
    },
    "Vivian": {
        "Visão computacional": 4.5,
        "Design": 2.5,
        "Redes neurais": 3.0,
        "Desenvolvimento de jogos": 1.5,
        "Desenvolvimento Web": 2.5,
        "Data science": 1.0,
        "Automação de testes": 4.5,
    },
}
